import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :example_service, ExampleServiceWeb.Endpoint,
  check_origin: [
    "//example_service.staging.stord.com",
    "//example_service.stord.com",
    "//*.nonprod.example_service.stord.com"
  ],
  http: [port: 4000],
  server: true

# Do not print debug messages in production
config :phoenix, :logger, false

config :logger,
  backends: [LoggerJSON],
  level: :info

config :example_service,
  cors_origin: ~r{^https?://(example_service(.*.?)|[\w-]*.nonprod.example_service).stord.com$}

config :example_service, ExampleServiceEvents.Producer, adapter: Kafee.Producer.AsyncAdapter

config :example_service, ExampleServiceEvents.Consumer, adapter: Kafee.Consumer.BroadwayAdapter
